// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	tools "github.com/rafaehl/tools-manager/tools"
	mock "github.com/stretchr/testify/mock"
)

// ToolsFetcher is an autogenerated mock type for the ToolsFetcher type
type ToolsFetcher struct {
	mock.Mock
}

// FetchTools provides a mock function with given fields: ctx, tag
func (_m *ToolsFetcher) FetchTools(ctx context.Context, tag string) ([]tools.Tool, error) {
	ret := _m.Called(ctx, tag)

	var r0 []tools.Tool
	if rf, ok := ret.Get(0).(func(context.Context, string) []tools.Tool); ok {
		r0 = rf(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tools.Tool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
