// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	tools "github.com/rafaehl/tools-manager/tools"
	mock "github.com/stretchr/testify/mock"
)

// ToolsCreator is an autogenerated mock type for the ToolsCreator type
type ToolsCreator struct {
	mock.Mock
}

// CreateTool provides a mock function with given fields: ctx, tool
func (_m *ToolsCreator) CreateTool(ctx context.Context, tool tools.Tool) error {
	ret := _m.Called(ctx, tool)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, tools.Tool) error); ok {
		r0 = rf(ctx, tool)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
